name: Medal Overlay For Streamlabs Chatbot
on:
  push:
    branches:
      - develop
jobs:
  buildPackage:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.semvers.outputs.patch }} # set the app_version to be the PATCH updated version
      tag: ${{ steps.semvers.outputs.v_patch }} # set the tag to be the PATCH updated version.
    env:
      GITHUB_TOKEN: "${{ github.token }}"
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    # Get the current tag
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.1.0 # Optional fallback tag to use when no tag can be found
    # calculate the next version
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - run: echo "app_version ${{ steps.semvers.outputs.patch }}"
    - name: Package Release
      id: packageRelease
      uses: camalot/chatbot-github-package-action@develop
      with:
        folderName: MedalOverlay
        repoName: chatbot-medaloverlay
        token: ${{ github.token }}
        version: ${{ steps.semvers.outputs.patch }}
    - run: 'echo "releaseZip: ${{ steps.packageRelease.outputs.releaseZip }}"'
